### ISSUE TITLE
Missing source for quotes

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/editor#33] opened 2023-04-14 13:54 UTC
When quoting a message, the source (Author / Link) is missing. These can be set manually, and the information will be displayed correctly. They are just missing, when the quote is inserted into the editor.

**Comment by dtdesign** [comment] 2023-04-14 14:06
I cannot confirm this, is this possibly a duplicate of #32?

**Comment by SoftCreatR** [comment] 2023-04-14 14:10
This is the current behavior after applying the latest changes:

![image](https://user-images.githubusercontent.com/81188/232068308-2b035eb8-86fc-4ff2-a271-85e663a36497.png)

As you can see, the quote is now properly inserted into the editor, but neither the author, nor the URL are filled in. We will investigate this further, and let you know.

**Comment by dtdesign** [comment] 2023-04-14 16:28
I have tested this once more with a clean installation using the Core’s `master` as well as a fresh build of the editor’s `main`.   It is important that you do not use the bundled CKEditor build because it is outdated and uses slightly different markup for quotes – earlier versions used regular attributes instead of `data-`-attributes.

**Comment by SoftCreatR** [comment] 2023-04-14 16:39
Alright. I'll wait for an updated build, and let you know.

**Comment by dtdesign** [comment] 2023-04-14 16:46
We’re not updating the bundled build on a regular basis during development.

You can run `npm run build` to create the latest bundle yourself. It will emit `dist/ckeditor.bundle.js` that you can use to replace the file in `js/3rdParty/ckeditor/`. Please be advised that you need to bump the `LAST_UPDATE_TIME` (incrementing by 1 is sufficient) to force a cache update in the browser.

**Comment by SoftCreatR** [comment] 2023-04-14 16:53
The latter usually happens automatically for us. But thanks for the hint.

**Comment by SoftCreatR** [comment] 2023-04-14 17:47
The current artifact (https://github.com/WoltLab/editor/actions/runs/4702014004) should do it as well, right?

**Comment by mutec** [comment] 2023-04-14 18:56
Or, you could wait for me building the whole stuff again. :P

**Comment by dtdesign** [comment] 2023-04-27 16:06
I have pushed an updated bundle with https://github.com/WoltLab/WCF/commit/6fc5d54f6f5249d552860af4f65fa385188bd293.

**Closed by dtdesign** 2023-04-27 16:06 UTC
